import type { ComplaintRequirement } from '../models/complaint-requirement.model';

export const DUMMY_COMPLAINT_REQUIREMENTS: ComplaintRequirement[] = [
  {
    Id: 'req-01',
    Name: 'رقم الموعد',
    Required: true,
    Type: 'text',
    Value: null,
    ReadOnly: false,
    Options: [],
  },
  {
    Id: 'req-02',
    Name: 'نوع الإشكالية',
    Required: true,
    Type: 'dropdown',
    Value: null,
    ReadOnly: false,
    Options: [
      'وصول رسالة عدم الحضور علماً انه تم الحضور',
      'وصول رسالة تم الحضور علماً بانه لم يتم الحجز أو الحضور',
    ],
  },
  {
    Id: 'req-03',
    Name: 'اسم العيادة',
    Required: false,
    Type: 'text',
    Value: null,
    ReadOnly: false,
    Options: [],
  },
  {
    Id: 'req-04',
    Name: 'اسم المركز / المستشفى',
    Required: true,
    Type: 'text',
    Value: null,
    ReadOnly: false,
    Options: [],
  },
  {
    Id: 'req-05',
    Name: 'تاريخ الموعد',
    Required: true,
    Type: 'date',
    Value: null,
    ReadOnly: false,
    Options: [],
  },
  {
    Id: 'req-06',
    Name: 'هل لديك مرفقات داعمة؟',
    Required: true,
    Type: 'radio',
    Value: null,
    ReadOnly: false,
    Options: ['نعم', 'لا'],
  },
  {
    Id: 'req-07',
    Name: 'المرفقات الداعمة',
    Required: false,
    Type: 'file',
    Value: null,
    ReadOnly: false,
    Options: [],
  },
];
