import type { LookupItem } from '../models/lookup.model';

export const DUMMY_REGIONS: LookupItem[] = [
  { Name: 'الرياض',            Value: 'region-01' },
  { Name: 'مكة المكرمة',       Value: 'region-02' },
  { Name: 'المدينة المنورة',   Value: 'region-03' },
  { Name: 'المنطقة الشرقية',   Value: 'region-04' },
  { Name: 'القصيم',            Value: 'region-05' },
  { Name: 'عسير',              Value: 'region-06' },
  { Name: 'تبوك',              Value: 'region-07' },
  { Name: 'حائل',              Value: 'region-08' },
  { Name: 'الحدود الشمالية',   Value: 'region-09' },
  { Name: 'جازان',             Value: 'region-10' },
  { Name: 'نجران',             Value: 'region-11' },
  { Name: 'الباحة',            Value: 'region-12' },
  { Name: 'الجوف',             Value: 'region-13' },
];

export const DUMMY_CITIES: LookupItem[] = [
  { Name: 'الرياض',          Value: 'city-01' },
  { Name: 'جدة',             Value: 'city-02' },
  { Name: 'مكة المكرمة',     Value: 'city-03' },
  { Name: 'المدينة المنورة', Value: 'city-04' },
  { Name: 'الدمام',          Value: 'city-05' },
  { Name: 'الخبر',           Value: 'city-06' },
  { Name: 'الطائف',          Value: 'city-07' },
  { Name: 'بريدة',           Value: 'city-08' },
  { Name: 'تبوك',            Value: 'city-09' },
  { Name: 'أبها',            Value: 'city-10' },
  { Name: 'خميس مشيط',      Value: 'city-11' },
  { Name: 'حائل',            Value: 'city-12' },
  { Name: 'ينبع',            Value: 'city-13' },
  { Name: 'الأحساء',         Value: 'city-14' },
  { Name: 'القطيف',          Value: 'city-15' },
  { Name: 'الجبيل',          Value: 'city-16' },
  { Name: 'نجران',           Value: 'city-17' },
  { Name: 'جازان',           Value: 'city-18' },
];

export const DUMMY_COMPLAINT_CATEGORIES: LookupItem[] = [
  { Name: 'جودة الخدمة',           Value: 'category-01' },
  { Name: 'تأخر في تقديم الخدمة',  Value: 'category-02' },
  { Name: 'رسوم غير صحيحة',        Value: 'category-03' },
  { Name: 'سوء المعاملة',          Value: 'category-04' },
  { Name: 'عدم توفر الخدمة',       Value: 'category-05' },
  { Name: 'أخرى',                  Value: 'category-06' },
];

export const DUMMY_COUNTRIES: LookupItem[] = [
  { Name: 'السعودية',          Value: 'country-01' },
  { Name: 'مصر',               Value: 'country-02' },
  { Name: 'الأردن',            Value: 'country-03' },
  { Name: 'سوريا',             Value: 'country-04' },
  { Name: 'اليمن',             Value: 'country-05' },
  { Name: 'السودان',           Value: 'country-06' },
  { Name: 'باكستان',           Value: 'country-07' },
  { Name: 'الهند',             Value: 'country-08' },
  { Name: 'بنغلاديش',          Value: 'country-09' },
  { Name: 'الفلبين',           Value: 'country-10' },
  { Name: 'إندونيسيا',         Value: 'country-11' },
  { Name: 'إثيوبيا',           Value: 'country-12' },
  { Name: 'تركيا',             Value: 'country-13' },
  { Name: 'المغرب',            Value: 'country-14' },
  { Name: 'الجزائر',           Value: 'country-15' },
  { Name: 'تونس',              Value: 'country-16' },
  { Name: 'الكويت',            Value: 'country-17' },
  { Name: 'الإمارات',          Value: 'country-18' },
  { Name: 'قطر',               Value: 'country-19' },
  { Name: 'البحرين',           Value: 'country-20' },
  { Name: 'عُمان',             Value: 'country-21' },
  { Name: 'العراق',            Value: 'country-22' },
  { Name: 'لبنان',             Value: 'country-23' },
  { Name: 'فلسطين',            Value: 'country-24' },
  { Name: 'الولايات المتحدة',  Value: 'country-25' },
  { Name: 'المملكة المتحدة',   Value: 'country-26' },
  { Name: 'فرنسا',             Value: 'country-27' },
  { Name: 'ألمانيا',           Value: 'country-28' },
];
