import type { LookupItem } from '../models/lookup.model';

export const DUMMY_REGIONS: LookupItem[] = [
  { name: 'الرياض',            value: 'region-01' },
  { name: 'مكة المكرمة',       value: 'region-02' },
  { name: 'المدينة المنورة',   value: 'region-03' },
  { name: 'المنطقة الشرقية',   value: 'region-04' },
  { name: 'القصيم',            value: 'region-05' },
  { name: 'عسير',              value: 'region-06' },
  { name: 'تبوك',              value: 'region-07' },
  { name: 'حائل',              value: 'region-08' },
  { name: 'الحدود الشمالية',   value: 'region-09' },
  { name: 'جازان',             value: 'region-10' },
  { name: 'نجران',             value: 'region-11' },
  { name: 'الباحة',            value: 'region-12' },
  { name: 'الجوف',             value: 'region-13' },
];

export const DUMMY_CITIES: LookupItem[] = [
  { name: 'الرياض',          value: 'city-01' },
  { name: 'جدة',             value: 'city-02' },
  { name: 'مكة المكرمة',     value: 'city-03' },
  { name: 'المدينة المنورة', value: 'city-04' },
  { name: 'الدمام',          value: 'city-05' },
  { name: 'الخبر',           value: 'city-06' },
  { name: 'الطائف',          value: 'city-07' },
  { name: 'بريدة',           value: 'city-08' },
  { name: 'تبوك',            value: 'city-09' },
  { name: 'أبها',            value: 'city-10' },
  { name: 'خميس مشيط',      value: 'city-11' },
  { name: 'حائل',            value: 'city-12' },
  { name: 'ينبع',            value: 'city-13' },
  { name: 'الأحساء',         value: 'city-14' },
  { name: 'القطيف',          value: 'city-15' },
  { name: 'الجبيل',          value: 'city-16' },
  { name: 'نجران',           value: 'city-17' },
  { name: 'جازان',           value: 'city-18' },
];

export const DUMMY_COUNTRIES: LookupItem[] = [
  { name: 'السعودية',          value: 'country-01' },
  { name: 'مصر',               value: 'country-02' },
  { name: 'الأردن',            value: 'country-03' },
  { name: 'سوريا',             value: 'country-04' },
  { name: 'اليمن',             value: 'country-05' },
  { name: 'السودان',           value: 'country-06' },
  { name: 'باكستان',           value: 'country-07' },
  { name: 'الهند',             value: 'country-08' },
  { name: 'بنغلاديش',          value: 'country-09' },
  { name: 'الفلبين',           value: 'country-10' },
  { name: 'إندونيسيا',         value: 'country-11' },
  { name: 'إثيوبيا',           value: 'country-12' },
  { name: 'تركيا',             value: 'country-13' },
  { name: 'المغرب',            value: 'country-14' },
  { name: 'الجزائر',           value: 'country-15' },
  { name: 'تونس',              value: 'country-16' },
  { name: 'الكويت',            value: 'country-17' },
  { name: 'الإمارات',          value: 'country-18' },
  { name: 'قطر',               value: 'country-19' },
  { name: 'البحرين',           value: 'country-20' },
  { name: 'عُمان',             value: 'country-21' },
  { name: 'العراق',            value: 'country-22' },
  { name: 'لبنان',             value: 'country-23' },
  { name: 'فلسطين',            value: 'country-24' },
  { name: 'الولايات المتحدة',  value: 'country-25' },
  { name: 'المملكة المتحدة',   value: 'country-26' },
  { name: 'فرنسا',             value: 'country-27' },
  { name: 'ألمانيا',           value: 'country-28' },
];
