import { RelatedTicket } from './related-ticket.model';

export interface ComplainDetailsData {
  ServiceProviderId:           string | null;
  EntityTypeId:                string | null;
  EntityType:                  string | null;
  MainServiceId:               string | null;
  MainService:                 string | null;
  SubServiceId:                string | null;
  SubService:                  string | null;
  ComplaintCategoryId:         string | null;
  ComplaintCategory:           string | null;
  ComplaintMainCategoryId:     string | null;
  ComplaintMainCategory:       string | null;
  ComplaintSubCategoryId:      string | null;
  ComplaintSubCategory:        string | null;
  ComplaintSubCategoryClassId: string | null;
  ComplaintSubCategoryClass:   string | null;
  RegionId:                    string | null;
  Region:                      string | null;
  CommercialRecord:            string | null;
  CommercialRecordId:          string | null;
  CustomerId:                  string | null;
  IsAttached:                  boolean;
  RelatedTicketIds:            string[] | null;
  ComplainQuestions:           Record<string, string | string[]> | null;
  AgentQuestionnaire:          string | null;
  QuestionIds:                 string[] | null;
  CustomerName:                string | null;
  ServiceProviderName:         string | null;
  MainServiceName:             string | null;
  SubServiceName:              string | null;
  ComplaintCategoryName:       string | null;
  CommercialRecordName:        string | null;
  RegionName:                  string | null;
  ComplaintSubCategoryName:    string | null;
  ComplaintMainCategoryName:   string | null;
  RelatedTickets:              RelatedTicket[] | null;
  Questions:                   unknown;
  EntityTypeName:              string | null;
  TicketNumber:                string | null;
  Title:                       string | null;
  Subject:                     string | null;
  Description:                 string | null;
  Origin:                      string | null;
  CreatedBy:                   string | null;
  CreatedByContact:            string | null;
  CreatedByName:               string | null;
  Status:                      string | null;
  CaseCurrentStatus:           string | null;
  EntityId?:                   string;
  ComplainId?:                 string;
  CreatedOn:                   string | null;
  ModifiedByName:              string | null;
  ModifiedOn:                  string | null;
}
